[project]
name = "rag-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ahmad Alhineidi", email = "ahmad.alhineidi@unibe.ch" }
]
requires-python = ">=3.12"
dependencies = [
    "chromadb==1.5.9",
    "django==6.0.6",
    "django-environ==0.13.0",
    "langchain-community<0.4.2",
    "markdown-it-py>=4.2.0",
    "nltk==3.9.4",
    "ollama==0.6.2",
    "openai==2.41.1",
    "pdfplumber==0.11.10",
    "python-docx==1.2.0",
    "python-dotenv==1.2.2",
    "ragas>=0.4.0",
    "rank-bm25>=0.2.2",
    "sentence-transformers==5.6.0",
    "tiktoken>=0.14.0",
    "tqdm==4.68.2",
]

[project.scripts]
rag-framework = "rag_framework:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
